# Generated by Django 6.0.7 on 2026-07-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.aiinstruction'),
        ),
    ]
